# Generated by Django 5.1.1 on 2024-10-04 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_referral"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="referral",
            name="success",
            field=models.BooleanField(default=False),
        ),
    ]
