# Generated by Django 5.1.1 on 2024-10-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0006_tag_blog_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
